In [ ]:
import numpy as np
n1 = np.array([1,2,3,4])
print(n1)
print(n1.size)
print(type(n1))
print(n1.ndim)
# all execution are part of EDA

[1 2 3 4]
4
<class 'numpy.ndarray'>
1


In [ ]:
n2 = np.array([[1,2,3,4],[5,6,7,8]])  # model always accept 2-d array
print(n2)
print(n2.size)
print(type(n2))
print(n2.ndim)


[[1 2 3 4]
 [5 6 7 8]]
8
<class 'numpy.ndarray'>
2


In [ ]:
n3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(n3)
print(n3.size)
print(type(n3))
print(n3.ndim)
# in case you 3-D array then must be convert into 2-d 
# then model trained


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
9
<class 'numpy.ndarray'>
3


In [ ]:
n4 = np.array([[[[1,2,3],[4,5,6],[7,8,9],[4,6,8]]]])
print(n4)
print(n4.size)
print(type(n4))
print(n4.ndim)
# ml does not support 4-d array

[[[[1 2 3]
   [4 5 6]
   [7 8 9]
   [4 6 8]]]]
12
<class 'numpy.ndarray'>
4


In [ ]:
import numpy as np
n5 = np.array(list(map(int,input("enter elemnts ").split())))
print(n5)


In [3]:
n = int(input("enter number of elements"))
n5 = np.array([int(input()) for i in range (n)])
print(n5)

[3 3 4 7]


In [4]:
rows = int(input("Enter number of rows"))
cols = int(input("Enter number of cols"))
t =[]
for i in range(rows):
    t1=[]
    for j in range(cols):
        v = int(input("enter elements"))
        t1.append(v)
    
    t.append(t1)
n6 = np.array(t)
print(n6)

ValueError: invalid literal for int() with base 10: ''

In [3]:
# method ML,DL,AI
# zeros is used to receive sensor data(camera)
z = np.zeros(4)
print(z)
z2=np.zeros((4,4))
print(z2)



[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
# is udes to availability like product,loan,prediction
# 0 and 1 is mostly used in binary classification
t1 = np.ones(4)
print(t1)
t2 = np.ones((3,4))
print(t2)

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
# identity matrix is used for co relation 
# in Ml eye replace with t3.corr() method
t3 = np.eye(3)
print(t3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
# why slicing in numpy
a1 = np.array([1,2,3,4,5,6,7,8,9])
a2 = np.array([[1,2,3,4],[5,6,7,8]])
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])


In [7]:
import numpy as np

a3 = np.array([
    [ [1,2,3], [4,5,6], [7,8,9] ]])

print(a3[0, :, :][[0, 1, 2], [2, 1, 0]])
print(a3[0, 1, :])

[3 5 7]
[4 5 6]


In [8]:
import numpy as np

a1 = np.array([1,2,3,4,5,6,7,8,9])

# Indexing
print("Element 3:", a1[2])
print("Element 7:", a1[6])

# Slicing
print("2, 3, 4:", a1[1:4])
print("1, 2, 3, 4, 5:", a1[:5])
print("6, 7, 8, 9:", a1[5:])
print("1, 3, 5, 7, 9:", a1[::2])

a2 = np.array([ [1,2,3,4], [5,6,7,8]])

# Indexing
print("Element 3:", a2[0,2])
print("Element 7:", a2[1,2])

# Slicing
print("First row:", a2[0,:])
print("Second row:", a2[1,:])

print("First column:", a2[:,0])
print("Last column:", a2[:,3])


Element 3: 3
Element 7: 7
2, 3, 4: [2 3 4]
1, 2, 3, 4, 5: [1 2 3 4 5]
6, 7, 8, 9: [6 7 8 9]
1, 3, 5, 7, 9: [1 3 5 7 9]
Element 3: 3
Element 7: 7
First row: [1 2 3 4]
Second row: [5 6 7 8]
First column: [1 5]
Last column: [4 8]


In [10]:
# 7th what is the first work in ML 
# shape and reshape 
x = np.arange(1, 9)
y = x.reshape(2, 2, 2)
print(y)
print(y.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


In [ ]:
# njext is age and salary, bonus, gross salary, net salary ( inc or dec)
# in product , if purchase 10000 then free delivery 
# in product , if purchase 5000 then 5% discount 
a = np.array([1,2,3,4,5,6])
x = a + 2
y = a * 2
print(x)
print(y)

[3 4 5 6 7 8]
[ 2  4  6  8 10 12]


In [14]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
a2 = np.array([11,22,33,44])
z1 = a1 + a2
print(z1)
z2 = a1 / a2
print(z2)

[[12 24 36 48]
 [16 28 40 52]]
[[0.09090909 0.09090909 0.09090909 0.09090909]
 [0.45454545 0.27272727 0.21212121 0.18181818]]
