In [5]:
import numpy as np
n = np.array([1,2,3,4,5,6,7,8,9,9,9])
print(np.sum(n))
print(np.max(n))
print(np.min(n))
print(np.mean(n))
print(np.median(n))
print(np.size(n))

63
9
1
5.7272727272727275
6.0
11


In [6]:
n = np.array([10,20,30,40,50])
print(np.cumsum(n))
print(np.cumprod(n))

[ 10  30  60 100 150]
[      10      200     6000   240000 12000000]


In [8]:
t = np.array([[1,2],[4,5]])
print(np.cumsum(t))
print(np.cumprod(t))

[ 1  3  7 12]
[ 1  2  8 40]


In [9]:
r = np.array([[[1,2],[3,4],[5,6]]])
print(np.cumsum(r))
print(np.cumprod(r))

[ 1  3  6 10 15 21]
[  1   2   6  24 120 720]


In [11]:
# axis = 0 means up and down 
# axis = 1 means left to right 
n = np.array([[10,20,30],
              [40,50,60]])
print(n)
print(np.sum(n,axis = 0))
print (np.sum(n,axis = 1))

[[10 20 30]
 [40 50 60]]
[50 70 90]
[ 60 150]


In [12]:
n = np.array([[[1,2],[3,4],[5,6]]])
print(n)
print(np.sum(n,axis=0))
print(np.sum(n,axis = 1))

[[[1 2]
  [3 4]
  [5 6]]]
[[1 2]
 [3 4]
 [5 6]]
[[ 9 12]]


In [18]:
# pandas is used for perform operation on dataset 
# there are two types 
# 1. Series (1-D) 2. Dataframe(2-D)
import pandas as pd
import numpy as np
s1 = pd.Series()
print(s1)
s2 = np.array([1,2,3,4,5])
s3 = pd.Series(s2)
print(s3)
s4 = pd.Series([11,22,33,44])
print(s4)

Series([], dtype: object)
0    1
1    2
2    3
3    4
4    5
dtype: int64
0    11
1    22
2    33
3    44
dtype: int64


In [19]:
s5 = pd.Series(["aman","chaman","monu","sonu"], index = ["A","B","C","D"])
print(s5)

A      aman
B    chaman
C      monu
D      sonu
dtype: object


In [ ]:
s6 = pd.Series([10,20,30,40,50])
print(s6.index)
print(s6.shape)  # for dimension 
print(s6.size)
print(s6.values)
print(s6.dtype) # tyoe for data ML

RangeIndex(start=0, stop=5, step=1)
(5,)
5
[10 20 30 40 50]
int64


In [24]:
# 1 way 2D dataset 
data = [
    [1,"david","developer",23000,"noida"],
    [2,"pitter","programmer",45000,"delhi"],
    [3,"kumar","hr",32000,"banglore"],
    [4,"sahil","trainee",16000,"chennai"],
    [5,"hari","manger",50000,"delhi"]
]
df = pd.DataFrame(data)
df = pd.DataFrame(data,columns=["Id","Name","Post","Salary","City"])
print(df)


   Id    Name        Post  Salary      City
0   1   david   developer   23000     noida
1   2  pitter  programmer   45000     delhi
2   3   kumar          hr   32000  banglore
3   4   sahil     trainee   16000   chennai
4   5    hari      manger   50000     delhi


In [31]:
# 2nd ways 2D dataset 
emp = {
    "id":[1,2,3,4,5],
    "name":["ram","shyam","nikhil","david","pitter"],
    "post":["devloper","hr","clerk","programmer","trainee"],
    "salary":[2300,3400,1200,3200,1700],
    "city":["noida","delhi","gurgaon","faridabad","mohali"]

}
df = pd.DataFrame(emp)
print(df["name"])
# get top 2 
print(df.head(2))
# get last two 
print(df.tail(2))
# whose salry greater than 2000
print(df[df["salary"]>2000])
# get salary btw 3500 to 2500
df[(df["salary"]<3500) & (df["salary"]>2000)]


0       ram
1     shyam
2    nikhil
3     david
4    pitter
Name: name, dtype: object
   id   name      post  salary   city
0   1    ram  devloper    2300  noida
1   2  shyam        hr    3400  delhi
   id    name        post  salary       city
3   4   david  programmer    3200  faridabad
4   5  pitter     trainee    1700     mohali
   id   name        post  salary       city
0   1    ram    devloper    2300      noida
1   2  shyam          hr    3400      delhi
3   4  david  programmer    3200  faridabad


,id,name,post,salary,city
0,1,ram,devloper,2300,noida
1,2,shyam,hr,3400,delhi
3,4,david,programmer,3200,faridabad


In [35]:
# how to get max,min salary 
print(df["salary"].max())
print(df["salary"].min())
# how to get name,post and salary
print(df[["name","post","salary"]])
# how to add column 


3400
1200
     name        post  salary
0     ram    devloper    2300
1   shyam          hr    3400
2  nikhil       clerk    1200
3   david  programmer    3200
4  pitter     trainee    1700


In [ ]:
# client mostly ask each and every months \
# give me 10 pandas dataset like id , name , post, salary, city and age 

# 1. add columns bonus > = 40000  5% 
# 2. ------- hra 10% 
# 3. -------- da 5 % 
# 4. calculate gross salary 
# 5. calculate net salary 
import pandas as pd

# Employee dataset
data = {
    "id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "name": ["Rahul", "Neha", "Vikram", "Pooja", "Rohan",
             "Sneha", "Arjun", "Kavya", "Varun", "Megha"],
    "post": ["Manager", "Developer", "HR", "Tester", "Developer",
             "Designer", "Manager", "Developer", "Tester", "HR"],
    "salary": [60000, 50000, 45000, 38000, 55000,
               42000, 70000, 48000, 35000, 46000],
    "city": ["Delhi", "Mumbai", "Pune", "Jaipur", "Bangalore",
             "Chennai", "Hyderabad", "Pune", "Kolkata", "Delhi"],
    "age": [32, 25, 29, 24, 27, 26, 35, 23, 28, 30]
}

df = pd.DataFrame(data)

# 1. Bonus = 5% if salary >= 40000
df["bonus"] = df["salary"].apply(
    lambda x: x * 0.05 if x >= 40000 else 0
)

# 2. HRA = 10% of salary
df["hra"] = df["salary"] * 0.10

# 3. DA = 5% of salary
df["da"] = df["salary"] * 0.05

# 4. Gross Salary
df["gross_salary"] = (
    df["salary"] + df["bonus"] + df["hra"] + df["da"]
)

# 5. Net Salary
df["net_salary"] = df["gross_salary"]

print(df)


    id    name       post  salary       city  age   bonus     hra      da  \
0  101   Rahul    Manager   60000      Delhi   32  3000.0  6000.0  3000.0   
1  102    Neha  Developer   50000     Mumbai   25  2500.0  5000.0  2500.0   
2  103  Vikram         HR   45000       Pune   29  2250.0  4500.0  2250.0   
3  104   Pooja     Tester   38000     Jaipur   24     0.0  3800.0  1900.0   
4  105   Rohan  Developer   55000  Bangalore   27  2750.0  5500.0  2750.0   
5  106   Sneha   Designer   42000    Chennai   26  2100.0  4200.0  2100.0   
6  107   Arjun    Manager   70000  Hyderabad   35  3500.0  7000.0  3500.0   
7  108   Kavya  Developer   48000       Pune   23  2400.0  4800.0  2400.0   
8  109   Varun     Tester   35000    Kolkata   28     0.0  3500.0  1750.0   
9  110   Megha         HR   46000      Delhi   30  2300.0  4600.0  2300.0   

   gross_salary  net_salary  
0       72000.0     72000.0  
1       60000.0     60000.0  
2       54000.0     54000.0  
3       43700.0     43700.0  
4 

In [ ]:
# product id, name,price,quantity total price 
# 1. add column total price 5000 then 10% otherwise 5% 
#2. ----------- total 2000 free delivery 
#3. ----------- gst apply on total_price  with 8% 
import pandas as pd

data = {
    "product_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "name": [
        "Laptop", "Headphones", "Keyboard", "Monitor", "Mouse",
        "Smartphone", "Tablet", "Printer", "Webcam", "Speaker"
    ],
    "price": [55000, 2500, 1800, 12000, 900, 45000, 22000, 8500, 3500, 4000],
    "quantity": [2, 3, 5, 2, 4, 1, 2, 1, 3, 2]
}

df = pd.DataFrame(data)

# Calculate total price
df["total_price"] = df["price"] * df["quantity"]

print(df)

   product_id        name  price  quantity  total_price
0         101      Laptop  55000         2       110000
1         102  Headphones   2500         3         7500
2         103    Keyboard   1800         5         9000
3         104     Monitor  12000         2        24000
4         105       Mouse    900         4         3600
5         106  Smartphone  45000         1        45000
6         107      Tablet  22000         2        44000
7         108     Printer   8500         1         8500
8         109      Webcam   3500         3        10500
9         110     Speaker   4000         2         8000
